@HabitTracker_HostAddress = https://localhost:7213
@AccessToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWFyaWExMjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhQGIuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJiOWJkYWZlNi0xYTc3LTRlNzAtZjI0MC0wOGRlMTFhNzlkYTAiLCJqdGkiOiI4ZjQ3YTgyYy0wMzI4LTQwMTQtOGQ2MC01NGM0ZjU0YzAxNTciLCJleHAiOjE3NjE5NDA2NzYsImlzcyI6IkhhYml0IFRyYWNrZXIgQVBJIiwiYXVkIjoiVXNlcnMifQ.k6DgDf0hKyCYth5ncucd6p_54nJpF20j7KfbqxINMYegCLV3n3vW9piDBwwN0vP5WRbKvoEbP9dIgmSh4_3y8w
@RefreshToken = f51595cc-c1c0-4959-b6b3-d9ddfb0dd9f4-32830d5b-c499-4d52-9241-834c35b90680

POST {{HabitTracker_HostAddress}}/api/auth/register
Content-Type: application/json

{
    "username": "maria123",
    "email": "a@b.com",
    "password": "135236"
}

###
POST {{HabitTracker_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "userIdentifier": "maria123",
    "password": "135236"
}

###
POST {{HabitTracker_HostAddress}}/api/auth/refresh
Authorization: bearer {{AccessToken}}
Content-Type: application/json

{
    "accessToken": "{{AccessToken}}",
    "refreshToken": "{{RefreshToken}}"
}

###
GET {{HabitTracker_HostAddress}}/api/auth/ping
Authorization: bearer {{AccessToken}}

###
POST {{HabitTracker_HostAddress}}/api/habits
Authorization: bearer {{AccessToken}}
Content-Type: application/json

{
    "name": "gym",
    "color": "#ff00f",
    "emoji": ":)",
    "target": 10,
    "frequencyInDays": 30,
    "AllowCustomValue": true,
    "AllowExceedTarget": true
}

###
GET {{HabitTracker_HostAddress}}/api/Habits/1f6909d8-8afd-4e32-9936-08de119f1b7f
Authorization: bearer {{AccessToken}}

###
GET {{HabitTracker_HostAddress}}/api/Habits
Authorization: bearer {{AccessToken}}

###

PATCH {{HabitTracker_HostAddress}}/api/Habits/b6d867bd-0042-423f-31eb-08de17244819/track/2025/6/days/increment
Authorization: bearer {{AccessToken}}
Content-Type: application/json

{
    "dayUpdates": {
        "31": "4"
    }
}