@HabitTracker_HostAddress = https://localhost:7213
@AccessToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWFnaTEyMyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFAYS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImM2ODNiOTJlLWM2ZjMtNDZjMS03MDJhLTA4ZGUxMDQ1ZTRhZiIsImp0aSI6ImZkMTVkNWY3LWI0NTMtNGU5ZC1hYmJkLThkNjkxM2QwMThmZiIsImV4cCI6MTc2MTAyOTI4MCwiaXNzIjoiSGFiaXQgVHJhY2tlciBBUEkiLCJhdWQiOiJVc2VycyJ9.Em7lhNJrYLK1s0Dwf8e_hRMqZdnIBMHDLUUbJzgjxZrObPKR8x_dlikN_f1ImYanVEMib28l0-yIsw8NwFABRg
@RefreshToken = f3cdd17f-f6b8-43a1-a5ce-852aae40c6b4-bf190f99-0ec7-4c21-9cde-a976f26cb6a9

POST {{HabitTracker_HostAddress}}/api/auth/register
Content-Type: application/json

{
    "username": "magi123",
    "email": "a@a.com",
    "password": "135236"
}

###
POST {{HabitTracker_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "userIdentifier": "magi123",
    "password": "123456"
}

###
POST {{HabitTracker_HostAddress}}/api/auth/refresh
Authorization: bearer {{AccessToken}}
Content-Type: application/json

{
    "accessToken": "{{AccessToken}}",
    "refreshToken": "{{RefreshToken}}"
}

###
GET {{HabitTracker_HostAddress}}/api/auth/ping
Authorization: bearer {{AccessToken}}
