@HabitTracker_HostAddress = https://localhost:7213
@AccessToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWFyaWExMjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhQGIuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJiOWJkYWZlNi0xYTc3LTRlNzAtZjI0MC0wOGRlMTFhNzlkYTAiLCJqdGkiOiI0N2QwYWI5MS0yNDVkLTQ3ZDctOWI0ZS1kNzFlYTFjMWI3Y2YiLCJleHAiOjE3NjE4NTg3NTEsImlzcyI6IkhhYml0IFRyYWNrZXIgQVBJIiwiYXVkIjoiVXNlcnMifQ.Z7xeY9bd79Tpz09IMhwMLHzcjJSd2EZE8tt2NrQ25yEAStbco5DezKXByrZcYB3rADIyNlCDyfRBOGc514ryMw
@RefreshToken = 2ba345d1-7f14-4600-9c32-b365519057b1-d0e31118-58b6-46e4-ac2e-8eddfa772608

POST {{HabitTracker_HostAddress}}/api/auth/register
Content-Type: application/json

{
    "username": "maria123",
    "email": "a@b.com",
    "password": "135236"
}

###
POST {{HabitTracker_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "userIdentifier": "maria123",
    "password": "135236"
}

###
POST {{HabitTracker_HostAddress}}/api/auth/refresh
Authorization: bearer {{AccessToken}}
Content-Type: application/json

{
    "accessToken": "{{AccessToken}}",
    "refreshToken": "{{RefreshToken}}"
}

###
GET {{HabitTracker_HostAddress}}/api/auth/ping
Authorization: bearer {{AccessToken}}

###
POST {{HabitTracker_HostAddress}}/api/habits
Authorization: bearer {{AccessToken}}
Content-Type: application/json

{
    "name": "gym",
    "color": "#ff00f",
    "emoji": ":)",
    "target": 10,
    "frequencyInDays": 30,
    "AllowCustomValue": true,
    "AllowExceedTarget": true
}

###
GET {{HabitTracker_HostAddress}}/api/Habits/1f6909d8-8afd-4e32-9936-08de119f1b7f
Authorization: bearer {{AccessToken}}

###
GET {{HabitTracker_HostAddress}}/api/Habits
Authorization: bearer {{AccessToken}}

###

PATCH {{HabitTracker_HostAddress}}/api/Habits/b6d867bd-0042-423f-31eb-08de17244819/track/2025/6/days/increment
Authorization: bearer {{AccessToken}}
Content-Type: application/json

{
    "dayUpdates": {
        "31": "1.5"
    }
}